# location of test src
TEST_SRC_PREFIX	:= $(TOP_PREFIX)test/

# grin suffix as generated by ehc
TEST_GRIN_SUFFIX	:= grin2

# this file
TEST_MKF							:= $(TEST_SRC_PREFIX)files.mk

# main + sources + dpds, for .chs
TEST_ALL_SRC						:= $(wildcard $(TEST_SRC_PREFIX)*.eh)
TEST_EXP_DRV						:= $(wildcard $(TEST_SRC_PREFIX)*.eh.exp*)

# distribution
TEST_DIST_FILES						:= $(TEST_ALL_SRC) $(TEST_EXP_DRV) $(TEST_MKF)

# rules
test-lists:
	@cd $(TEST_SRC_PREFIX) ; \
	shopt -s nullglob ; \
	for v in $(EHC_VARIANTS) ; \
	do \
	  ehs= ; \
	  vv=`echo $$v | sed -e 's/_[0-9]//'` ; \
	  for ((i = 1 ; i <= $${vv} ; i++)) ; do ehs="$$ehs `echo $${i}/*.{eh,hs}`" ; done ; \
	  echo "$$ehs" > $$v.lst ; \
	done

test-expect test-regress: test-lists
	@how=`echo $@ | sed -e 's/.*expect.*/exp/' -e 's/.*regress.*/reg/'` ; \
	cd $(TEST_SRC_PREFIX) ; \
	for v in $(VERSIONS) ; \
	do \
	  echo "== version $$v ==" ; \
	  ehc=../bin/$$v/$(EHC_EXEC_NAME)$(EXEC_SUFFIX) ; \
	  gri=../bin/$$v/$(GRINI_EXEC_NAME)$(EXEC_SUFFIX) ; \
	  if test -x $$ehc ; \
	  then \
	    if test "x$${TEST_FILES}" = "x" ; \
	    then \
	      TEST_FILES=`cat $$v.lst` ; \
	    fi ; \
	    for t in $${TEST_FILES} ; \
	    do \
	      cleanup="rm -f" ; \
	      tdir=`dirname $$t` ; \
	      tb="$${tdir}/"`basename $$t .eh` ; \
	      tsuff=".eh" ; \
	      if test $${tb} = $${t} ; \
	      then \
	        tb="$${tdir}/"`basename $$t .hs` ; \
	        tsuff=".hs" ; \
	      fi ; \
	      if test -r $$t -a -x $$ehc ; \
	      then \
	        tprelbase=`sed -n -E 's/^-- %% *inline test *\(([a-z0-9]+)\) --$$/\1/p' < $$t` ; \
	        tprel="$${v}-$${tprelbase}$${tsuff}" ; \
	        if test -r $${tprel} ; \
	        then \
	          tb2="$${tb}+p" ; \
	          t2="$${tb2}$${tsuff}" ; \
	          cat $${tprel} $${t} > $${t2} ; \
	          cleanup="$${cleanup} $${t2}" ; \
	        else \
	          tb2="$${tb}" ; \
	          t2="$${t}" ; \
	        fi ; \
	        te=$${t}.exp$${v} ; tr=$${t}.reg$${v} ; th=$${t}.$${how}$${v} ; \
	        tc=$${tb2}.core ; tg=$${tb2}.$(TEST_GRIN_SUFFIX) ; \
	        rm -f $${tc} $${tg} ; \
	        $$ehc $${t2} > $${th} 2>&1 ; \
	        if test -r $${tc} ; \
	        then \
	          echo "== core ==" >> $${th} ; \
	          cat $${tc} >> $${th} ; \
	          if test -x $$gri -a "x$(CORE_TARG_SUFFIX)" = "x$(TEST_GRIN_SUFFIX)" ; \
	          then \
	            rm -f $${tg} ; \
	            $$ehc --code=grin $${t2} > /dev/null ; \
	            echo "== grin execution ==" >> $${th} ; \
	            $$gri $${tg} >> $${th} 2>&1 ; \
	          fi \
	        fi ; \
	        if test $${tr} = $${th} -a -r $${te} ; \
	        then \
	          echo "-- $${te} -- $${th} --" | $(INDENT2) ; \
	          if cmp $${te} $${th} > /dev/null ; \
	          then \
	            echo -n ; \
	          else \
	            diff $${te} $${th} | $(INDENT4) ; \
	          fi \
	        elif test ! -r $${te} ; \
	        then \
	          echo "-- no $${te} to compare to" | $(INDENT2) ; \
	        fi \
	      fi ; \
	      $${cleanup} ; \
	    done \
	  else \
	    echo "-- no $$ehc to compile with" | $(INDENT2) ; \
	  fi \
	done
