# location of agprimer src
SRC_AGPRIMER_PREFIX	:= $(SRC_PREFIX)agprimer/

# this file
AGPRIMER_MKF				:= $(SRC_AGPRIMER_PREFIX)files.mk

# main + sources
AGPRIMER_HS_REPM_SRC_CHS	:= $(SRC_AGPRIMER_PREFIX)RepminHS.chs
AGPRIMER_AG_REPM_SRC_CAG	:= $(SRC_AGPRIMER_PREFIX)RepminAG.cag
AGPRIMER_AG_EXPR_SRC_CAG	:= $(SRC_AGPRIMER_PREFIX)AGPrimerExpr.cag

AGPRIMER_CAG_SRC_CAG		:= $(AGPRIMER_AG_REPM_SRC_CAG) $(AGPRIMER_AG_EXPR_SRC_CAG)
AGPRIMER_CHS_SRC_CHS		:= $(AGPRIMER_HS_REPM_SRC_CHS)

# derived sources
AGPRIMER_HS_REPM_DRV_HS		:= $(AGPRIMER_HS_REPM_SRC_CHS:.chs=.hs)

AGPRIMER_AG_REPM_DRV_AG		:= $(AGPRIMER_AG_REPM_SRC_CAG:.cag=.ag)
AGPRIMER_AG_REPM_DRV_HS		:= $(AGPRIMER_AG_REPM_SRC_CAG:.cag=.hs)

AGPRIMER_AG_EXPR_DRV_AG		:= $(AGPRIMER_AG_EXPR_SRC_CAG:.cag=.ag)
AGPRIMER_AG_EXPR_DRV_HS		:= $(AGPRIMER_AG_EXPR_SRC_CAG:.cag=.hs)

# binary/executable
AGPRIMER_HS_REPM_BLD_EXEC		:= $(BLD_BIN_PREFIX)repminhs$(EXEC_SUFFIX)
AGPRIMER_AG_REPM_BLD_EXEC		:= $(BLD_BIN_PREFIX)repminag$(EXEC_SUFFIX)
AGPRIMER_AG_EXPR_BLD_EXEC		:= $(BLD_BIN_PREFIX)expr$(EXEC_SUFFIX)

# shuffle order
AGPRIMER_SHUFFLE_ORDER	:= 1 < 2

# chunks for inclusion in main text by shuffle
AGPRIMER_ALL_CHUNK_SRC		:= $(AGPRIMER_CAG_SRC_CAG) $(AGPRIMER_CHS_SRC_CHS)

# distribution
AGPRIMER_DIST_FILES			:= $(AGPRIMER_CAG_SRC_CAG) $(AGPRIMER_CHS_SRC_CHS) $(AGPRIMER_MKF)

# make rules
$(AGPRIMER_HS_REPM_BLD_EXEC): $(AGPRIMER_HS_REPM_DRV_HS)
	mkdir -p $(@D)
	$(GHC) --make $(GHC_OPTS) -i$(SRC_AGPRIMER_PREFIX) $< -o $@

$(AGPRIMER_AG_REPM_BLD_EXEC): $(AGPRIMER_AG_REPM_DRV_HS)
	mkdir -p $(@D)
	$(GHC) --make $(GHC_OPTS) -i$(SRC_AGPRIMER_PREFIX) $< -o $@

$(AGPRIMER_AG_EXPR_BLD_EXEC): $(AGPRIMER_AG_EXPR_DRV_HS)
	mkdir -p $(@D)
	$(GHC) --make $(GHC_OPTS) -i$(SRC_AGPRIMER_PREFIX) $< -o $@

$(AGPRIMER_AG_EXPR_DRV_HS) $(AGPRIMER_AG_REPM_DRV_HS) : %.hs : %.ag
	$(AGC) -csdfr $(UUAGC_OPTS_WHEN_EHC) -P$(SRC_AGPRIMER_PREFIX) $<

$(AGPRIMER_HS_REPM_DRV_HS): %.hs : %.chs $(SHUFFLE)
	$(SHUFFLE_HS) --gen=1 --base=Main --order="$(AGPRIMER_SHUFFLE_ORDER)" $< > $@

$(AGPRIMER_AG_REPM_DRV_AG) $(AGPRIMER_AG_EXPR_DRV_AG): %.ag: %.cag $(SHUFFLE)
	$(SHUFFLE_AG) --gen=1 --base=Main --order="$(AGPRIMER_SHUFFLE_ORDER)" $< > $@








