# variant, see ../ehc/variant.mk, which is assumed to be included before this one
EHC_BLD_LIBGRINC_VARIANT_PREFIX			:= $(EHC_BLD_VARIANT_PREFIX)lib-grinc/

# lib/cabal/module config
LIB_GRINC_BASE							:= GRIN
LIB_GRINC_QUAL							:= $(subst _,x,$(LIB_GRINC_BASE)$(EHC_VARIANT))
LIB_GRINC_QUAL_PREFIX					:= $(LIB_GRINC_QUAL).
LIB_GRINC_HS_PREFIX						:= $(subst .,$(PATH_SEP),$(LIB_GRINC_QUAL_PREFIX))
LIB_GRINC_PKG_NAME						:= $(subst .,-,$(LIB_GRINC_QUAL))
LIB_GRINC_INS_FLAG						:= $(INSABS_FLAG_PREFIX)$(LIB_GRINC_PKG_NAME)

# installation
INS_GRINC_LIB_PREFIX					:= $(INSABS_PREFIX)lib/$(LIB_GRINC_PKG_NAME)-$(EH_VERSION)/
INS_GRINC_LIB_AG_PREFIX					:= $(INS_GRINC_LIB_PREFIX)ag/

# further derived info
GRINC_BLD_LIB_HS_VARIANT_PREFIX			:= $(EHC_BLD_LIBGRINC_VARIANT_PREFIX)$(LIB_GRINC_HS_PREFIX)
SRC_GRINC_LIB_PREFIX					:= $(SRC_GRINC_PREFIX)$(LIB_GRINC_BASE)

# tool use
LIB_GRINC_SHUFFLE_DEFS					:= --def=GRIN:$(LIB_GRINC_QUAL_PREFIX)
