# variant, to be configured on top level
INF2PS_VARIANT								:= X
INF2PS_VARIANT_EXTRA						:= i
INF2PS_VARIANT_PREFIX						:= $(INF2PS_VARIANT_EXTRA)$(INF2PS_VARIANT)/
INF2PS_BLD_VARIANT_PREFIX					:= $(BLD_PREFIX)$(INF2PS_VARIANT_PREFIX)
INF2PS_BIN_PREFIX							:= $(BIN_PREFIX)
INF2PS_BLD_BIN_VARIANT_PREFIX				:= $(INF2PS_BIN_PREFIX)$(INF2PS_VARIANT_PREFIX)
INF2PS_VARIANT_RULER_SEL					:= ().().()

# all variants
INF2PS_VARIANTS								:= 1 2 3
