# location of infer2pass src
SRC_INF2PS_PREFIX						:= $(SRC_PREFIX)infer2pass/

# location of infer2pass build
#INF2PS_BLD_PREFIX						:= $(BLD_PREFIX)infer2pass/

# end products, binary, executable, etc
INF2PS_EXEC_NAME						:= infer2pass
INF2PS_BLD_EXEC							:= $(INF2PS_BLD_BIN_VARIANT_PREFIX)$(INF2PS_EXEC_NAME)$(EXEC_SUFFIX)
INF2PS_ALL_EXECS						:= $(patsubst %,$(INF2PS_BIN_PREFIX)$(INF2PS_VARIANT_EXTRA)%/$(INF2PS_EXEC_NAME)$(EXEC_SUFFIX),$(INF2PS_VARIANTS))

# shuffle order
INF2PS_SHUFFLE_ORDER					:= 1 < 2 < 3

# this file
INF2PS_MKF								:= $(SRC_INF2PS_PREFIX)files.mk

# main + sources + dpds
INF2PS_MAIN								:= Infer2Pass

INF2PS_RL_RULES_BASE					:= RulerInfer2Pass
INF2PS_RL_RULES_SRC_CRUL				:= $(addprefix $(SRC_INF2PS_PREFIX),$(INF2PS_RL_RULES_BASE).crul)
INF2PS_RL_RULES_DRV_RUL					:= $(patsubst $(SRC_INF2PS_PREFIX)%.crul,$(INF2PS_BLD_VARIANT_PREFIX)%.rul,$(INF2PS_RL_RULES_SRC_CRUL))
INF2PS_RL_RULES_DRV_AG					:= $(INF2PS_RL_RULES_DRV_RUL:.rul=.ag)

INF2PS_HS_MAIN_SRC_CHS					:= $(addprefix $(SRC_INF2PS_PREFIX),$(INF2PS_MAIN).chs)
INF2PS_HS_MAIN_DRV_HS					:= $(patsubst $(SRC_INF2PS_PREFIX)%.chs,$(INF2PS_BLD_VARIANT_PREFIX)%.hs,$(INF2PS_HS_MAIN_SRC_CHS))
INF2PS_HS_DPDS_SRC_CHS					:= $(patsubst %,$(SRC_INF2PS_PREFIX)%.chs,Infer2PassSupport Common Cnstr Substitutable)
INF2PS_HS_DPDS_DRV_HS					:= $(patsubst $(SRC_INF2PS_PREFIX)%.chs,$(INF2PS_BLD_VARIANT_PREFIX)%.hs,$(INF2PS_HS_DPDS_SRC_CHS))

INF2PS_AGMAIN_MAIN_SRC_CAG				:= $(patsubst %,$(SRC_INF2PS_PREFIX)%.cag,MainAG)
INF2PS_AGMAIN_MAIN_DRV_AG				:= $(patsubst $(SRC_INF2PS_PREFIX)%.cag,$(INF2PS_BLD_VARIANT_PREFIX)%.ag,$(INF2PS_AGMAIN_MAIN_SRC_CAG))
INF2PS_AGMAIN_DPDS_DRV_AG				:= $(patsubst %,$(INF2PS_BLD_VARIANT_PREFIX)%.ag,$(INF2PS_RL_RULES_BASE) \
											)
$(patsubst $(INF2PS_BLD_VARIANT_PREFIX)%.ag,$(INF2PS_BLD_VARIANT_PREFIX)%.hs,$(INF2PS_AGMAIN_MAIN_DRV_AG)) \
										: $(INF2PS_AGMAIN_DPDS_DRV_AG)

INF2PS_AGTY_MAIN_SRC_CAG				:= $(patsubst %,$(SRC_INF2PS_PREFIX)%.cag,Ty)
INF2PS_AGTY_DPDS_SRC_CAG				:= $(patsubst %,$(SRC_INF2PS_PREFIX)%.cag,TyAbsSyn)
$(patsubst $(SRC_INF2PS_PREFIX)%.cag,$(INF2PS_BLD_VARIANT_PREFIX)%.hs,$(INF2PS_AGTY_MAIN_SRC_CAG)) \
										: $(patsubst $(SRC_INF2PS_PREFIX)%.cag,$(INF2PS_BLD_VARIANT_PREFIX)%.ag,$(INF2PS_AGTY_DPDS_SRC_CAG))

INF2PS_AGTY_ELIMALT_MAIN_SRC_CAG		:= $(patsubst %,$(SRC_INF2PS_PREFIX)%.cag,TyElimAlts)
INF2PS_AGTY_ELIMALT_DPDS_SRC_CAG		:= $(patsubst %,$(SRC_INF2PS_PREFIX)%.cag,TyAbsSyn)
$(patsubst $(SRC_INF2PS_PREFIX)%.cag,$(INF2PS_BLD_VARIANT_PREFIX)%.hs,$(INF2PS_AGTY_ELIMALT_MAIN_SRC_CAG)) \
										: $(patsubst $(SRC_INF2PS_PREFIX)%.cag,$(INF2PS_BLD_VARIANT_PREFIX)%.ag,$(INF2PS_AGTY_ELIMALT_DPDS_SRC_CAG))

INF2PS_AGTY_SUBST_MAIN_SRC_CAG			:= $(patsubst %,$(SRC_INF2PS_PREFIX)%.cag,TyElimBoth)
INF2PS_AGTY_SUBST_DPDS_SRC_CAG			:= $(patsubst %,$(SRC_INF2PS_PREFIX)%.cag,TyAbsSyn)
$(patsubst $(SRC_INF2PS_PREFIX)%.cag,$(INF2PS_BLD_VARIANT_PREFIX)%.hs,$(INF2PS_AGTY_SUBST_MAIN_SRC_CAG)) \
										: $(patsubst $(SRC_INF2PS_PREFIX)%.cag,$(INF2PS_BLD_VARIANT_PREFIX)%.ag,$(INF2PS_AGTY_SUBST_DPDS_SRC_CAG))

INF2PS_AGTY_FTV_MAIN_SRC_CAG			:= $(patsubst %,$(SRC_INF2PS_PREFIX)%.cag,TySubst)
INF2PS_AGTY_FTV_DPDS_SRC_CAG			:= $(patsubst %,$(SRC_INF2PS_PREFIX)%.cag,TyAbsSyn)
$(patsubst $(SRC_INF2PS_PREFIX)%.cag,$(INF2PS_BLD_VARIANT_PREFIX)%.hs,$(INF2PS_AGTY_FTV_MAIN_SRC_CAG)) \
										: $(patsubst $(SRC_INF2PS_PREFIX)%.cag,$(INF2PS_BLD_VARIANT_PREFIX)%.ag,$(INF2PS_AGTY_FTV_DPDS_SRC_CAG))

INF2PS_AGTY_ELIMBOTH_MAIN_SRC_CAG		:= $(patsubst %,$(SRC_INF2PS_PREFIX)%.cag,TyFtv)
INF2PS_AGTY_ELIMBOTH_DPDS_SRC_CAG		:= $(patsubst %,$(SRC_INF2PS_PREFIX)%.cag,TyAbsSyn)
$(patsubst $(SRC_INF2PS_PREFIX)%.cag,$(INF2PS_BLD_VARIANT_PREFIX)%.hs,$(INF2PS_AGTY_ELIMBOTH_MAIN_SRC_CAG)) \
										: $(patsubst $(SRC_INF2PS_PREFIX)%.cag,$(INF2PS_BLD_VARIANT_PREFIX)%.ag,$(INF2PS_AGTY_ELIMBOTH_DPDS_SRC_CAG))

INF2PS_AG_D_MAIN_SRC_CAG				:= $(INF2PS_AGTY_MAIN_SRC_CAG)
INF2PS_AG_S_MAIN_SRC_CAG				:= $(INF2PS_AGTY_ELIMALT_MAIN_SRC_CAG) $(INF2PS_AGTY_ELIMBOTH_MAIN_SRC_CAG) \
											 $(INF2PS_AGTY_SUBST_MAIN_SRC_CAG) $(INF2PS_AGTY_FTV_MAIN_SRC_CAG)
INF2PS_AG_DS_MAIN_SRC_CAG				:= $(INF2PS_AGMAIN_MAIN_SRC_CAG)

INF2PS_AG_ALL_MAIN_SRC_CAG				:= $(INF2PS_AG_DS_MAIN_SRC_CAG) $(INF2PS_AG_S_MAIN_SRC_CAG) $(INF2PS_AG_D_MAIN_SRC_CAG)

INF2PS_AG_D_MAIN_DRV_AG					:= $(patsubst $(SRC_INF2PS_PREFIX)%.cag,$(INF2PS_BLD_VARIANT_PREFIX)%.ag,$(INF2PS_AG_D_MAIN_SRC_CAG))
INF2PS_AG_S_MAIN_DRV_AG					:= $(patsubst $(SRC_INF2PS_PREFIX)%.cag,$(INF2PS_BLD_VARIANT_PREFIX)%.ag,$(INF2PS_AG_S_MAIN_SRC_CAG))
INF2PS_AG_DS_MAIN_DRV_AG				:= $(patsubst $(SRC_INF2PS_PREFIX)%.cag,$(INF2PS_BLD_VARIANT_PREFIX)%.ag,$(INF2PS_AG_DS_MAIN_SRC_CAG))

INF2PS_AG_ALL_MAIN_DRV_AG				:= $(INF2PS_AG_D_MAIN_DRV_AG) $(INF2PS_AG_S_MAIN_DRV_AG) $(INF2PS_AG_DS_MAIN_DRV_AG)

INF2PS_AG_ALL_DPDS_SRC_CAG				:= $(sort \
											$(INF2PS_AGTY_DPDS_SRC_CAG) \
											$(INF2PS_AGTY_ELIMALT_DPDS_SRC_CAG) \
											$(INF2PS_AGTY_ELIMBOTH_DPDS_SRC_CAG) \
											$(INF2PS_AGTY_SUBST_DPDS_SRC_CAG) \
											$(INF2PS_AGTY_FTV_DPDS_SRC_CAG) \
											)

# all src
INF2PS_HS_ALL_SRC_CHS					:= $(INF2PS_HS_DPDS_SRC_CHS) $(INF2PS_HS_MAIN_SRC_CHS)
INF2PS_ALL_CHUNK_SRC					:= $(INF2PS_AG_ALL_MAIN_SRC_CAG) $(INF2PS_AG_ALL_DPDS_SRC_CAG) $(INF2PS_HS_ALL_SRC_CHS)
INF2PS_ALL_SRC							:= $(INF2PS_ALL_CHUNK_SRC) $(INF2PS_RL_RULES_SRC_CRUL)

# derived
INF2PS_AG_D_MAIN_DRV_HS					:= $(patsubst $(INF2PS_BLD_VARIANT_PREFIX)%.ag,$(INF2PS_BLD_VARIANT_PREFIX)%.hs,$(INF2PS_AG_D_MAIN_DRV_AG))
INF2PS_AG_S_MAIN_DRV_HS					:= $(patsubst $(INF2PS_BLD_VARIANT_PREFIX)%.ag,$(INF2PS_BLD_VARIANT_PREFIX)%.hs,$(INF2PS_AG_S_MAIN_DRV_AG))
INF2PS_AG_DS_MAIN_DRV_HS				:= $(patsubst $(INF2PS_BLD_VARIANT_PREFIX)%.ag,$(INF2PS_BLD_VARIANT_PREFIX)%.hs,$(INF2PS_AG_DS_MAIN_DRV_AG))
INF2PS_AG_ALL_MAIN_DRV_HS				:= $(INF2PS_AG_D_MAIN_DRV_HS) $(INF2PS_AG_S_MAIN_DRV_HS) $(INF2PS_AG_DS_MAIN_DRV_HS)

INF2PS_HS_ALL_DRV_HS					:= $(INF2PS_HS_MAIN_DRV_HS) $(INF2PS_HS_DPDS_DRV_HS)

INF2PS_AG_ALL_DPDS_DRV_AG				:= $(patsubst $(SRC_INF2PS_PREFIX)%.cag,$(INF2PS_BLD_VARIANT_PREFIX)%.ag,$(INF2PS_AG_ALL_DPDS_SRC_CAG))

# distribution
INF2PS_DIST_FILES						:= $(INF2PS_ALL_SRC) $(INF2PS_MKF)

# all dependents for a variant to kick of building
INF2PS_ALL_DPDS							:= $(INF2PS_HS_ALL_DRV_HS) $(INF2PS_AG_ALL_MAIN_DRV_HS)

# what is based on which Ruler view
INF2PS_ON_RULES_VIEW_1					:= HM
INF2PS_ON_RULES_VIEW_2					:= I1
INF2PS_ON_RULES_VIEW_3					:= I2

INF2PS_BY_RULER_GROUPS_BASE				:= expr.base tyexpr.base prog

INF2PS_BY_RULER_RULES_BASE				:= *
INF2PS_BY_RULER_RULES_3					:= $(INF2PS_BY_RULER_RULES_BASE)
INF2PS_BY_RULER_RULES_2					:= $(INF2PS_BY_RULER_RULES_3)
INF2PS_BY_RULER_RULES_1					:= $(INF2PS_BY_RULER_RULES_2)

# variant dispatch rules
$(patsubst $(BIN_PREFIX)$(INF2PS_VARIANT_EXTRA)%$(EXEC_SUFFIX),%,$(INF2PS_ALL_EXECS)): %: $(BIN_PREFIX)$(INF2PS_VARIANT_EXTRA)%$(EXEC_SUFFIX)

$(INF2PS_ALL_EXECS): %: $(INF2PS_ALL_SRC) $(INF2PS_MKF)
	$(MAKE) INF2PS_VARIANT=`echo $(notdir $(*D)) | sed -e 's/^$(INF2PS_VARIANT_EXTRA)//'` infer2pass-variant

# make rules
infer2pass-variant: 
	$(MAKE) INF2PS_VARIANT_RULER_SEL="(($(INF2PS_VARIANT)=$(INF2PS_ON_RULES_VIEW_$(INF2PS_VARIANT)))).($(INF2PS_BY_RULER_GROUPS_BASE)).($(INF2PS_BY_RULER_RULES_$(INF2PS_VARIANT)))" \
	  infer2pass-variant-dflt

infer2pass-variant-dflt: $(INF2PS_ALL_DPDS) $(LIB_EH_UTIL_INS_FLAG) lib-eh-4_2
	mkdir -p $(dir $(INF2PS_BLD_EXEC))
	$(GHC) --make $(GHC_OPTS) -package $(LIB_EH_UTIL_PKG_NAME) -package $(call SUBS_US_X,EH4_2) -i$(INF2PS_BLD_VARIANT_PREFIX) $(INF2PS_BLD_VARIANT_PREFIX)$(INF2PS_MAIN).hs -o $(INF2PS_BLD_EXEC)

$(INF2PS_RL_RULES_DRV_AG): $(INF2PS_RL_RULES_DRV_RUL) $(RULER2)
	mkdir -p $(@D) ; \
	$(RULER2) $(RULER2_OPTS) --ag --ATTR --DATA --selrule="$(INF2PS_VARIANT_RULER_SEL)" --base=$(*F) $< > $@

$(INF2PS_AG_D_MAIN_DRV_HS): $(INF2PS_BLD_VARIANT_PREFIX)%.hs: $(INF2PS_BLD_VARIANT_PREFIX)%.ag
	mkdir -p $(@D) ; \
	$(AGC) -dr $(UUAGC_OPTS_WHEN_EHC) -P"$(SRC_INF2PS_PREFIX)" -P"$(INF2PS_BLD_VARIANT_PREFIX)" -o $@ $<

$(INF2PS_AG_S_MAIN_DRV_HS): $(INF2PS_BLD_VARIANT_PREFIX)%.hs: $(INF2PS_BLD_VARIANT_PREFIX)%.ag
	mkdir -p $(@D) ; \
	$(AGC) -cfspr $(UUAGC_OPTS_WHEN_EHC) -P"$(SRC_INF2PS_PREFIX)" -P"$(INF2PS_BLD_VARIANT_PREFIX)" -o $@ $<

$(INF2PS_AG_DS_MAIN_DRV_HS): $(INF2PS_BLD_VARIANT_PREFIX)%.hs: $(INF2PS_BLD_VARIANT_PREFIX)%.ag
	mkdir -p $(@D) ; \
	$(AGC) -dcfspr $(UUAGC_OPTS_WHEN_EHC) -P"$(SRC_INF2PS_PREFIX)" -P"$(INF2PS_BLD_VARIANT_PREFIX)" -o $@ $<

#$(INF2PS_HS_ALL_DRV_HS): $(INF2PS_BLD_VARIANT_PREFIX)%.hs: $(SRC_INF2PS_PREFIX)%.hs
#	mkdir -p $(@D) ; \
#	cp $< $@

$(INF2PS_HS_MAIN_DRV_HS): $(INF2PS_BLD_VARIANT_PREFIX)%.hs: $(SRC_INF2PS_PREFIX)%.chs $(SHUFFLE)
	mkdir -p $(@D)
	$(SHUFFLE_HS) --gen=$(INF2PS_VARIANT) --base=Main --order="$(INF2PS_SHUFFLE_ORDER)" $< > $@

$(INF2PS_HS_DPDS_DRV_HS): $(INF2PS_BLD_VARIANT_PREFIX)%.hs: $(SRC_INF2PS_PREFIX)%.chs $(SHUFFLE)
	mkdir -p $(@D)
	$(SHUFFLE_HS) --gen=$(INF2PS_VARIANT) --base=$(*F) --order="$(INF2PS_SHUFFLE_ORDER)" $< > $@

$(INF2PS_AG_ALL_MAIN_DRV_AG) $(INF2PS_AG_ALL_DPDS_DRV_AG): $(INF2PS_BLD_VARIANT_PREFIX)%.ag: $(SRC_INF2PS_PREFIX)%.cag $(SHUFFLE)
	mkdir -p $(@D)
	$(SHUFFLE_AG) --gen=$(INF2PS_VARIANT) --base=$(*F) --order="$(INF2PS_SHUFFLE_ORDER)" $< > $@

$(INF2PS_RL_RULES_DRV_RUL): $(INF2PS_BLD_VARIANT_PREFIX)%.rul: $(SRC_INF2PS_PREFIX)%.crul $(SHUFFLE)
	mkdir -p $(@D)
	$(SHUFFLE) --gen=1 --base=$(*F) --plain --preamble=no --lhs2tex=no --order="1" $< > $@

