# variant, to be configured on top level
EHC_VARIANT								:= X
EHC_VARIANT_PREFIX						:= $(EHC_VARIANT)/
EHC_BLD_VARIANT_PREFIX					:= $(BLD_PREFIX)$(EHC_VARIANT_PREFIX)
EHC_BIN_PREFIX							:= $(BIN_PREFIX)
EHC_BLD_BIN_VARIANT_PREFIX				:= $(EHC_BIN_PREFIX)$(EHC_VARIANT_PREFIX)
EHC_VARIANT_RULER_SEL					:= ().().()

