RULER3_MAIN1AG_MAIN_SRC_AG := $(patsubst %,$(SRC_RULER3_PREFIX)%.cag,Main1AG)
RULER3_MAIN1AG_DPDS_SRC_AG := $(patsubst %,$(RULER3_BLD_PREFIX)%.ag, AbsSyn/AbsSyn1AG AbsSyn/CommonAG FmGamAG AS1/Misc AS1/ViewDpd AS1/SchemeDpd AS1/Pretty AS1/RlSel AS1/GenAS2 Expr/AbsSynAG Expr/IsRwAG Expr/NmSAG Expr/FmGamAG Expr/PrettyPrintAG Expr/SelfAG Ty/AbsSynAG Ty/SelfAG)
$(patsubst $(SRC_RULER3_PREFIX)%.ag,$(RULER3_BLD_PREFIX)%.hs,$(RULER3_MAIN1AG_MAIN_SRC_AG)) : $(RULER3_MAIN1AG_DPDS_SRC_AG)

RULER3_AS1_IMPORTS_MAIN_SRC_AG := $(patsubst %,$(SRC_RULER3_PREFIX)%.cag,AS1/Imports)
RULER3_AS1_IMPORTS_DPDS_SRC_AG := $(patsubst %,$(RULER3_BLD_PREFIX)%.ag, AbsSyn/AbsSyn1AG AbsSyn/CommonAG Expr/AbsSynAG)
$(patsubst $(SRC_RULER3_PREFIX)%.ag,$(RULER3_BLD_PREFIX)%.hs,$(RULER3_AS1_IMPORTS_MAIN_SRC_AG)) : $(RULER3_AS1_IMPORTS_DPDS_SRC_AG)

RULER3_MAIN2AG_MAIN_SRC_AG := $(patsubst %,$(SRC_RULER3_PREFIX)%.cag,Main2AG)
RULER3_MAIN2AG_DPDS_SRC_AG := $(patsubst %,$(RULER3_BLD_PREFIX)%.ag, AbsSyn/AbsSyn2AG AbsSyn/CommonAG FmGamAG AS2/Opts AS2/Pretty Expr/AbsSynAG Expr/PrettyPrintAG Expr/SelfAG Expr/FmGamAG ARule/AbsSynAG ARule/PrettyPrintAG ARule/SelfAG ARule/FmGamAG)
$(patsubst $(SRC_RULER3_PREFIX)%.ag,$(RULER3_BLD_PREFIX)%.hs,$(RULER3_MAIN2AG_MAIN_SRC_AG)) : $(RULER3_MAIN2AG_DPDS_SRC_AG)

RULER3_TRFAS2_GENARULE_MAIN_SRC_AG := $(patsubst %,$(SRC_RULER3_PREFIX)%.cag,TrfAS2/GenARule)
RULER3_TRFAS2_GENARULE_DPDS_SRC_AG := $(patsubst %,$(RULER3_BLD_PREFIX)%.ag, AbsSyn/AbsSyn2AG AbsSyn/CommonAG AS2/Opts TrfAS2/CommonAG Expr/AbsSynAG Expr/SelfAG ARule/AbsSynAG ARule/SelfAG)
$(patsubst $(SRC_RULER3_PREFIX)%.ag,$(RULER3_BLD_PREFIX)%.hs,$(RULER3_TRFAS2_GENARULE_MAIN_SRC_AG)) : $(RULER3_TRFAS2_GENARULE_DPDS_SRC_AG)

RULER3_TRFAS2_GENLATEX_MAIN_SRC_AG := $(patsubst %,$(SRC_RULER3_PREFIX)%.cag,TrfAS2/GenLaTeX)
RULER3_TRFAS2_GENLATEX_DPDS_SRC_AG := $(patsubst %,$(RULER3_BLD_PREFIX)%.ag, AbsSyn/AbsSyn2AG AbsSyn/CommonAG AS2/Opts TrfAS2/CommonAG Expr/AbsSynAG Expr/SelfAG ARule/AbsSynAG ARule/SelfAG)
$(patsubst $(SRC_RULER3_PREFIX)%.ag,$(RULER3_BLD_PREFIX)%.hs,$(RULER3_TRFAS2_GENLATEX_MAIN_SRC_AG)) : $(RULER3_TRFAS2_GENLATEX_DPDS_SRC_AG)

RULER3_TY_PRETTYPRINT_MAIN_SRC_AG := $(patsubst %,$(SRC_RULER3_PREFIX)%.cag,Ty/PrettyPrint)
RULER3_TY_PRETTYPRINT_DPDS_SRC_AG := $(patsubst %,$(RULER3_BLD_PREFIX)%.ag, Ty/AbsSynAG Ty/PrettyPrintAG)
$(patsubst $(SRC_RULER3_PREFIX)%.ag,$(RULER3_BLD_PREFIX)%.hs,$(RULER3_TY_PRETTYPRINT_MAIN_SRC_AG)) : $(RULER3_TY_PRETTYPRINT_DPDS_SRC_AG)

RULER3_EXPR_ISRW_MAIN_SRC_AG := $(patsubst %,$(SRC_RULER3_PREFIX)%.cag,Expr/IsRw)
RULER3_EXPR_ISRW_DPDS_SRC_AG := $(patsubst %,$(RULER3_BLD_PREFIX)%.ag, Expr/AbsSynAG Expr/IsRwAG)
$(patsubst $(SRC_RULER3_PREFIX)%.ag,$(RULER3_BLD_PREFIX)%.hs,$(RULER3_EXPR_ISRW_MAIN_SRC_AG)) : $(RULER3_EXPR_ISRW_DPDS_SRC_AG)

RULER3_EXPR_NMS_MAIN_SRC_AG := $(patsubst %,$(SRC_RULER3_PREFIX)%.cag,Expr/NmS)
RULER3_EXPR_NMS_DPDS_SRC_AG := $(patsubst %,$(RULER3_BLD_PREFIX)%.ag, Expr/AbsSynAG Expr/NmSAG)
$(patsubst $(SRC_RULER3_PREFIX)%.ag,$(RULER3_BLD_PREFIX)%.hs,$(RULER3_EXPR_NMS_MAIN_SRC_AG)) : $(RULER3_EXPR_NMS_DPDS_SRC_AG)

RULER3_EXPR_LATEX_MAIN_SRC_AG := $(patsubst %,$(SRC_RULER3_PREFIX)%.cag,Expr/LaTeX)
RULER3_EXPR_LATEX_DPDS_SRC_AG := $(patsubst %,$(RULER3_BLD_PREFIX)%.ag, Expr/AbsSynAG Expr/OptsAG Expr/FmGamAG Expr/LaTeXAG)
$(patsubst $(SRC_RULER3_PREFIX)%.ag,$(RULER3_BLD_PREFIX)%.hs,$(RULER3_EXPR_LATEX_MAIN_SRC_AG)) : $(RULER3_EXPR_LATEX_DPDS_SRC_AG)

RULER3_EXPR_COGAM_MAIN_SRC_AG := $(patsubst %,$(SRC_RULER3_PREFIX)%.cag,Expr/CoGam)
RULER3_EXPR_COGAM_DPDS_SRC_AG := $(patsubst %,$(RULER3_BLD_PREFIX)%.ag, Expr/AbsSynAG)
$(patsubst $(SRC_RULER3_PREFIX)%.ag,$(RULER3_BLD_PREFIX)%.hs,$(RULER3_EXPR_COGAM_MAIN_SRC_AG)) : $(RULER3_EXPR_COGAM_DPDS_SRC_AG)

RULER3_VIEWSEL_SELF_MAIN_SRC_AG := $(patsubst %,$(SRC_RULER3_PREFIX)%.cag,ViewSel/Self)
RULER3_VIEWSEL_SELF_DPDS_SRC_AG := $(patsubst %,$(RULER3_BLD_PREFIX)%.ag, ViewSel/AbsSynAG)
$(patsubst $(SRC_RULER3_PREFIX)%.ag,$(RULER3_BLD_PREFIX)%.hs,$(RULER3_VIEWSEL_SELF_MAIN_SRC_AG)) : $(RULER3_VIEWSEL_SELF_DPDS_SRC_AG)

RULER3_VIEWSEL_NMS_MAIN_SRC_AG := $(patsubst %,$(SRC_RULER3_PREFIX)%.cag,ViewSel/NmS)
RULER3_VIEWSEL_NMS_DPDS_SRC_AG := $(patsubst %,$(RULER3_BLD_PREFIX)%.ag, ViewSel/AbsSynAG ViewSel/DpdGrAG ViewSel/NmSAG)
$(patsubst $(SRC_RULER3_PREFIX)%.ag,$(RULER3_BLD_PREFIX)%.hs,$(RULER3_VIEWSEL_NMS_MAIN_SRC_AG)) : $(RULER3_VIEWSEL_NMS_DPDS_SRC_AG)

RULER3_VIEWSEL_RLRNM_MAIN_SRC_AG := $(patsubst %,$(SRC_RULER3_PREFIX)%.cag,ViewSel/RlRnm)
RULER3_VIEWSEL_RLRNM_DPDS_SRC_AG := $(patsubst %,$(RULER3_BLD_PREFIX)%.ag, ViewSel/AbsSynAG)
$(patsubst $(SRC_RULER3_PREFIX)%.ag,$(RULER3_BLD_PREFIX)%.hs,$(RULER3_VIEWSEL_RLRNM_MAIN_SRC_AG)) : $(RULER3_VIEWSEL_RLRNM_DPDS_SRC_AG)

RULER3_VIEWSEL_RLISSEL_MAIN_SRC_AG := $(patsubst %,$(SRC_RULER3_PREFIX)%.cag,ViewSel/RlIsSel)
RULER3_VIEWSEL_RLISSEL_DPDS_SRC_AG := $(patsubst %,$(RULER3_BLD_PREFIX)%.ag, ViewSel/AbsSynAG ViewSel/DpdGrAG ViewSel/NmSAG)
$(patsubst $(SRC_RULER3_PREFIX)%.ag,$(RULER3_BLD_PREFIX)%.hs,$(RULER3_VIEWSEL_RLISSEL_MAIN_SRC_AG)) : $(RULER3_VIEWSEL_RLISSEL_DPDS_SRC_AG)

RULER3_VIEWSEL_PRETTYPRINT_MAIN_SRC_AG := $(patsubst %,$(SRC_RULER3_PREFIX)%.cag,ViewSel/PrettyPrint)
RULER3_VIEWSEL_PRETTYPRINT_DPDS_SRC_AG := $(patsubst %,$(RULER3_BLD_PREFIX)%.ag, ViewSel/AbsSynAG)
$(patsubst $(SRC_RULER3_PREFIX)%.ag,$(RULER3_BLD_PREFIX)%.hs,$(RULER3_VIEWSEL_PRETTYPRINT_MAIN_SRC_AG)) : $(RULER3_VIEWSEL_PRETTYPRINT_DPDS_SRC_AG)

RULER3_ARULE_PATTERNUNIQ_MAIN_SRC_AG := $(patsubst %,$(SRC_RULER3_PREFIX)%.cag,ARule/PatternUniq)
RULER3_ARULE_PATTERNUNIQ_DPDS_SRC_AG := $(patsubst %,$(RULER3_BLD_PREFIX)%.ag, Expr/AbsSynAG ARule/AbsSynAG Expr/OptsAG ARule/OptsAG Expr/FmGamAG ARule/FmGamAG ARule/CopyRuleNmAG)
$(patsubst $(SRC_RULER3_PREFIX)%.ag,$(RULER3_BLD_PREFIX)%.hs,$(RULER3_ARULE_PATTERNUNIQ_MAIN_SRC_AG)) : $(RULER3_ARULE_PATTERNUNIQ_DPDS_SRC_AG)

RULER3_ARULE_RWSUBST_MAIN_SRC_AG := $(patsubst %,$(SRC_RULER3_PREFIX)%.cag,ARule/RwSubst)
RULER3_ARULE_RWSUBST_DPDS_SRC_AG := $(patsubst %,$(RULER3_BLD_PREFIX)%.ag, Expr/AbsSynAG ARule/AbsSynAG Expr/OptsAG ARule/OptsAG Expr/FmGamAG ARule/FmGamAG Expr/RwExprGamAG)
$(patsubst $(SRC_RULER3_PREFIX)%.ag,$(RULER3_BLD_PREFIX)%.hs,$(RULER3_ARULE_RWSUBST_MAIN_SRC_AG)) : $(RULER3_ARULE_RWSUBST_DPDS_SRC_AG)

RULER3_ARULE_AVARRENAME_MAIN_SRC_AG := $(patsubst %,$(SRC_RULER3_PREFIX)%.cag,ARule/AVarRename)
RULER3_ARULE_AVARRENAME_DPDS_SRC_AG := $(patsubst %,$(RULER3_BLD_PREFIX)%.ag, Expr/AbsSynAG ARule/AbsSynAG Expr/SelfAG ARule/SelfAG ARule/EqnDest1NmAG ARule/InCompDestAG)
$(patsubst $(SRC_RULER3_PREFIX)%.ag,$(RULER3_BLD_PREFIX)%.hs,$(RULER3_ARULE_AVARRENAME_MAIN_SRC_AG)) : $(RULER3_ARULE_AVARRENAME_DPDS_SRC_AG)

RULER3_ARULE_ELIMCOPYRULE_MAIN_SRC_AG := $(patsubst %,$(SRC_RULER3_PREFIX)%.cag,ARule/ElimCopyRule)
RULER3_ARULE_ELIMCOPYRULE_DPDS_SRC_AG := $(patsubst %,$(RULER3_BLD_PREFIX)%.ag, Expr/AbsSynAG ARule/AbsSynAG Expr/SelfAG ARule/SelfAG ARule/CopyRuleNmAG ARule/EqnDest1NmAG ARule/InCompDestAG)
$(patsubst $(SRC_RULER3_PREFIX)%.ag,$(RULER3_BLD_PREFIX)%.hs,$(RULER3_ARULE_ELIMCOPYRULE_MAIN_SRC_AG)) : $(RULER3_ARULE_ELIMCOPYRULE_DPDS_SRC_AG)

RULER3_ARULE_ELIMWILDCASSIGN_MAIN_SRC_AG := $(patsubst %,$(SRC_RULER3_PREFIX)%.cag,ARule/ElimWildcAssign)
RULER3_ARULE_ELIMWILDCASSIGN_DPDS_SRC_AG := $(patsubst %,$(RULER3_BLD_PREFIX)%.ag, Expr/AbsSynAG ARule/AbsSynAG)
$(patsubst $(SRC_RULER3_PREFIX)%.ag,$(RULER3_BLD_PREFIX)%.hs,$(RULER3_ARULE_ELIMWILDCASSIGN_MAIN_SRC_AG)) : $(RULER3_ARULE_ELIMWILDCASSIGN_DPDS_SRC_AG)

RULER3_ARULE_PRETTYPRINT_MAIN_SRC_AG := $(patsubst %,$(SRC_RULER3_PREFIX)%.cag,ARule/PrettyPrint)
RULER3_ARULE_PRETTYPRINT_DPDS_SRC_AG := $(patsubst %,$(RULER3_BLD_PREFIX)%.ag, Expr/AbsSynAG ARule/AbsSynAG Expr/PrettyPrintAG ARule/PrettyPrintAG Expr/SelfAG ARule/SelfAG)
$(patsubst $(SRC_RULER3_PREFIX)%.ag,$(RULER3_BLD_PREFIX)%.hs,$(RULER3_ARULE_PRETTYPRINT_MAIN_SRC_AG)) : $(RULER3_ARULE_PRETTYPRINT_DPDS_SRC_AG)


RULER3_AG_S_DPDS_SRC_AG := $(sort $(RULER3_MAIN1AG_DPDS_SRC_AG) $(RULER3_AS1_IMPORTS_DPDS_SRC_AG) $(RULER3_MAIN2AG_DPDS_SRC_AG) $(RULER3_TRFAS2_GENARULE_DPDS_SRC_AG) $(RULER3_TRFAS2_GENLATEX_DPDS_SRC_AG) $(RULER3_TY_PRETTYPRINT_DPDS_SRC_AG) $(RULER3_EXPR_ISRW_DPDS_SRC_AG) $(RULER3_EXPR_NMS_DPDS_SRC_AG) $(RULER3_EXPR_LATEX_DPDS_SRC_AG) $(RULER3_EXPR_COGAM_DPDS_SRC_AG) $(RULER3_VIEWSEL_SELF_DPDS_SRC_AG) $(RULER3_VIEWSEL_NMS_DPDS_SRC_AG) $(RULER3_VIEWSEL_RLRNM_DPDS_SRC_AG) $(RULER3_VIEWSEL_RLISSEL_DPDS_SRC_AG) $(RULER3_VIEWSEL_PRETTYPRINT_DPDS_SRC_AG) $(RULER3_ARULE_PATTERNUNIQ_DPDS_SRC_AG) $(RULER3_ARULE_RWSUBST_DPDS_SRC_AG) $(RULER3_ARULE_AVARRENAME_DPDS_SRC_AG) $(RULER3_ARULE_ELIMCOPYRULE_DPDS_SRC_AG) $(RULER3_ARULE_ELIMWILDCASSIGN_DPDS_SRC_AG) $(RULER3_ARULE_PRETTYPRINT_DPDS_SRC_AG))

RULER3_AG_S_MAIN_SRC_AG := $(RULER3_MAIN1AG_MAIN_SRC_AG) $(RULER3_AS1_IMPORTS_MAIN_SRC_AG) $(RULER3_MAIN2AG_MAIN_SRC_AG) $(RULER3_TRFAS2_GENARULE_MAIN_SRC_AG) $(RULER3_TRFAS2_GENLATEX_MAIN_SRC_AG) $(RULER3_TY_PRETTYPRINT_MAIN_SRC_AG) $(RULER3_EXPR_ISRW_MAIN_SRC_AG) $(RULER3_EXPR_NMS_MAIN_SRC_AG) $(RULER3_EXPR_LATEX_MAIN_SRC_AG) $(RULER3_EXPR_COGAM_MAIN_SRC_AG) $(RULER3_VIEWSEL_SELF_MAIN_SRC_AG) $(RULER3_VIEWSEL_NMS_MAIN_SRC_AG) $(RULER3_VIEWSEL_RLRNM_MAIN_SRC_AG) $(RULER3_VIEWSEL_RLISSEL_MAIN_SRC_AG) $(RULER3_VIEWSEL_PRETTYPRINT_MAIN_SRC_AG) $(RULER3_ARULE_PATTERNUNIQ_MAIN_SRC_AG) $(RULER3_ARULE_RWSUBST_MAIN_SRC_AG) $(RULER3_ARULE_AVARRENAME_MAIN_SRC_AG) $(RULER3_ARULE_ELIMCOPYRULE_MAIN_SRC_AG) $(RULER3_ARULE_ELIMWILDCASSIGN_MAIN_SRC_AG) $(RULER3_ARULE_PRETTYPRINT_MAIN_SRC_AG)
