# location of infer2pass src
INF2PS_SRC_PREFIX	:= $(TOP_PREFIX)infer2pass/

# location of infer2pass build
INF2PS_BLD_PREFIX	:= $(BLD_PREFIX)infer2pass/

# this file
INF2PS_MKF			:= $(INF2PS_SRC_PREFIX)files.mk

# main + sources + dpds
INF2PS_MAIN			:= Infer2Pass

#INF2PS_AG_MAIN_SRC	:= $(addprefix $(INF2PS_SRC_PREFIX),$(INF2PS_MAIN).ag)

INF2PS_HS_MAIN_SRC_HS					:= $(addprefix $(INF2PS_SRC_PREFIX),$(INF2PS_MAIN).hs)
INF2PS_HS_MAIN_DRV_HS					:= $(patsubst $(INF2PS_SRC_PREFIX)%.hs,$(INF2PS_BLD_PREFIX)%.hs,$(INF2PS_HS_MAIN_SRC_HS))
INF2PS_HS_DPDS_SRC_HS					:= $(patsubst %,$(INF2PS_SRC_PREFIX)%.hs,Common ChunkParser CDocCommon)
INF2PS_HS_DPDS_DRV_HS					:= $(patsubst $(INF2PS_SRC_PREFIX)%.hs,$(INF2PS_BLD_PREFIX)%.hs,$(INF2PS_HS_DPDS_SRC_HS))

INF2PS_AGMAIN_MAIN_SRC_AG				:= $(patsubst %,$(INF2PS_SRC_PREFIX)%.ag,MainAG)
INF2PS_AGMAIN_DPDS_SRC_AG				:= $(patsubst %,$(INF2PS_SRC_PREFIX)%.ag,CDocAbsSyn ChunkAbsSyn \
											)
$(patsubst $(INF2PS_SRC_PREFIX)%.ag,$(INF2PS_BLD_PREFIX)%.hs,$(INF2PS_AGMAIN_MAIN_SRC_AG)) \
										: $(INF2PS_AGMAIN_DPDS_SRC_AG)

INF2PS_AGCDOC_MAIN_SRC_AG				:= $(patsubst %,$(INF2PS_SRC_PREFIX)%.ag,CDoc)
INF2PS_AGCDOC_DPDS_SRC_AG				:= $(patsubst %,$(INF2PS_SRC_PREFIX)%.ag,CDocAbsSyn)
$(patsubst $(INF2PS_SRC_PREFIX)%.ag,$(INF2PS_BLD_PREFIX)%.hs,$(INF2PS_AGCDOC_MAIN_SRC_AG)) \
										: $(INF2PS_AGCDOC_DPDS_SRC_AG)

INF2PS_CDSUBS_MAIN_SRC_AG				:= $(patsubst %,$(INF2PS_SRC_PREFIX)%.ag,CDocSubst)
INF2PS_CDSUBS_DPDS_SRC_AG				:= $(patsubst %,$(INF2PS_SRC_PREFIX)%.ag,CDocAbsSyn CDocCommonAG)
$(patsubst $(INF2PS_SRC_PREFIX)%.ag,$(INF2PS_BLD_PREFIX)%.hs,$(INF2PS_CDSUBS_MAIN_SRC_AG)) \
										: $(INF2PS_CDSUBS_DPDS_SRC_AG)

INF2PS_CDINLN_MAIN_SRC_AG				:= $(patsubst %,$(INF2PS_SRC_PREFIX)%.ag,CDocInline)
INF2PS_CDINLN_DPDS_SRC_AG				:= $(patsubst %,$(INF2PS_SRC_PREFIX)%.ag,CDocAbsSyn)
$(patsubst $(INF2PS_SRC_PREFIX)%.ag,$(INF2PS_BLD_PREFIX)%.hs,$(INF2PS_CDINLN_MAIN_SRC_AG)) \
										: $(INF2PS_CDINLN_DPDS_SRC_AG)

INF2PS_AG_D_MAIN_SRC_AG				:= $(INF2PS_AGCDOC_MAIN_SRC_AG)
INF2PS_AG_S_MAIN_SRC_AG				:= $(INF2PS_CDSUBS_MAIN_SRC_AG) $(INF2PS_CDINLN_MAIN_SRC_AG)
INF2PS_AG_DS_MAIN_SRC_AG				:= $(INF2PS_AGMAIN_MAIN_SRC_AG)

INF2PS_AG_ALL_DPDS_SRC_AG				:= $(sort \
											$(INF2PS_AGMAIN_DPDS_SRC_AG) \
											$(INF2PS_CDSUBS_DPDS_SRC_AG) \
											$(INF2PS_CDINLN_DPDS_SRC_AG) \
											$(INF2PS_AGCDOC_DPDS_SRC_AG) \
											)

INF2PS_AG_ALL_MAIN_SRC_AG				:= $(INF2PS_AG_D_MAIN_SRC_AG) $(INF2PS_AG_S_MAIN_SRC_AG) $(INF2PS_AG_DS_MAIN_SRC_AG)



# all src
INF2PS_ALL_SRC							:= $(INF2PS_AG_ALL_MAIN_SRC_AG) $(INF2PS_AG_ALL_DPDS_SRC_AG) $(INF2PS_HS_MAIN_SRC_HS) $(INF2PS_HS_DPDS_SRC_HS)

# derived
INF2PS_AG_D_MAIN_DRV_HS				:= $(patsubst $(INF2PS_SRC_PREFIX)%.ag,$(INF2PS_BLD_PREFIX)%.hs,$(INF2PS_AG_D_MAIN_SRC_AG))
INF2PS_AG_S_MAIN_DRV_HS				:= $(patsubst $(INF2PS_SRC_PREFIX)%.ag,$(INF2PS_BLD_PREFIX)%.hs,$(INF2PS_AG_S_MAIN_SRC_AG))
INF2PS_AG_DS_MAIN_DRV_HS				:= $(patsubst $(INF2PS_SRC_PREFIX)%.ag,$(INF2PS_BLD_PREFIX)%.hs,$(INF2PS_AG_DS_MAIN_SRC_AG))
INF2PS_AG_ALL_MAIN_DRV_HS				:= $(INF2PS_AG_D_MAIN_DRV_HS) $(INF2PS_AG_S_MAIN_DRV_HS) $(INF2PS_AG_DS_MAIN_DRV_HS)

INF2PS_HS_ALL_DRV_HS					:= $(INF2PS_HS_MAIN_DRV_HS) $(INF2PS_HS_DPDS_DRV_HS)

# binary/executable
INF2PS_BLD_EXEC	:= $(BIN_PREFIX)infer2pass$(EXEC_SUFFIX)
INF2PS				:= $(INF2PS_BLD_EXEC)

# distribution
INF2PS_DIST_FILES			:= $(INF2PS_ALL_SRC) $(INF2PS_MKF)

# make rules
$(INF2PS_BLD_EXEC): $(INF2PS_AG_ALL_MAIN_DRV_HS) $(INF2PS_HS_ALL_DRV_HS) $(LIB_SRC_HS)
	$(GHC) --make $(GHC_OPTS) $(GHC_OPTS_OPTIM) -i$(LIB_SRC_PREFIX) -i$(INF2PS_BLD_PREFIX) $(INF2PS_BLD_PREFIX)$(INF2PS_MAIN).hs -o $@
	strip $@

$(INF2PS_AG_D_MAIN_DRV_HS): $(INF2PS_BLD_PREFIX)%.hs: $(INF2PS_SRC_PREFIX)%.ag
	mkdir -p $(@D) ; \
	$(AGC) --module=$(*F) -dr -P$(INF2PS_SRC_PREFIX) -o $@ $<

$(INF2PS_AG_S_MAIN_DRV_HS): $(INF2PS_BLD_PREFIX)%.hs: $(INF2PS_SRC_PREFIX)%.ag
	mkdir -p $(@D) ; \
	$(AGC) -cfspr -P$(INF2PS_SRC_PREFIX) -o $@ $<

$(INF2PS_AG_DS_MAIN_DRV_HS): $(INF2PS_BLD_PREFIX)%.hs: $(INF2PS_SRC_PREFIX)%.ag
	mkdir -p $(@D) ; \
	$(AGC) --module=$(*F) -dcfspr -P$(INF2PS_SRC_PREFIX) -o $@ $<

$(INF2PS_HS_ALL_DRV_HS): $(INF2PS_BLD_PREFIX)%.hs: $(INF2PS_SRC_PREFIX)%.hs
	mkdir -p $(@D) ; \
	cp $< $@

