# location of GMP's src
SRC_EXTLIBS_GMP_PREFIX					:= $(TOP_PREFIX)extlibs/gmp/
SRCABS_EXTLIBS_GMP_PREFIX				:= $(TOPABS2_PREFIX)extlibs/gmp/

# this file
EXTLIBS_GMP_MKF							:= $(SRC_EXTLIBS_GMP_PREFIX)files.mk

# srcs
EXTLIBS_GMP_NAME						:= gmp-4.2.1
EXTLIBS_GMP_ARCHIVE						:= $(call WINXX_CYGWIN_NAME2,$(SRCABS_EXTLIBS_GMP_PREFIX)$(EXTLIBS_GMP_NAME).tar.gz)

# lib/cabal config
EXTLIBS_GMP_INSTALLFORBLD_FLAG			:= $(INSTALLFORBLDABS_FLAG_PREFIX)$(EXTLIBS_GMP_PKG_NAME)
EXTLIBS_GMP_INSTALL_FLAG				:= $(call FUN_INSTALLABS_FLAG_PREFIX,$(EHC_VARIANT_ASPECTS))$(EXTLIBS_GMP_PKG_NAME)

# options for C compiler
EHC_GCC_LD_OPTS							+= -l$(EXTLIBS_GMP_PKG_NAME)

# dependencies for rts
EHC_RTS_INSTALLFORBLD_DPDS_EXTLIBS		+= $(if $(findstring $(EHC_VARIANT),$(EHC_GMP_VARIANTS)),$(EXTLIBS_GMP_INSTALLFORBLD_FLAG),)
EHC_RTS_INSTALL_DPDS_EXTLIBS			+= $(if $(filter $(EHC_VARIANT),$(EHC_GMP_VARIANTS)),$(EXTLIBS_GMP_INSTALL_FLAG),)

# building location
BLDABS_EXTLIBS_GMP_PREFIX				:= $(BLDABS_PREFIX)gmp/

# install location
INSTALLFORBLDABS_EXTLIBS_GMP_PREFIX		:= $(INSTALLFORBLDABS_PREFIX)
INSTALLABS_EXTLIBS_GMP_PREFIX			:= $(call FUN_INSTALLABS_VARIANT_PREFIX,$(EHC_VARIANT_ASPECTS))
INSTALLABS_EXTLIBS_GMP_LIB_PREFIX		:= $(call FUN_INSTALLABS_VARIANT_LIB_SHARED_PREFIX,$(EHC_VARIANT_ASPECTS))
INSTALLABS_EXTLIBS_GMP_INC_PREFIX		:= $(call FUN_INSTALLABS_VARIANT_INC_SHARED_PREFIX,$(EHC_VARIANT_ASPECTS))

# distribution
LIBUTIL_DIST_FILES						:= $(EXTLIBS_GMP_MKF) $(EXTLIBS_GMP_ARCHIVE)

# target
lib-gmp: $(EXTLIBS_GMP_INSTALLFORBLD_FLAG)

# rules
$(EXTLIBS_GMP_INSTALLFORBLD_FLAG): $(EXTLIBS_GMP_ARCHIVE) $(EXTLIBS_GMP_MKF)
	mkdir -p $(BLDABS_EXTLIBS_GMP_PREFIX) && \
	cd $(BLDABS_EXTLIBS_GMP_PREFIX) && \
	tar xfz $(EXTLIBS_GMP_ARCHIVE) && \
	cd $(EXTLIBS_GMP_NAME) && \
	./configure --prefix=$(INSTALLFORBLDABS_EXTLIBS_GMP_PREFIX) && \
	make && \
	make install && \
	touch $@

$(EXTLIBS_GMP_INSTALL_FLAG): $(EXTLIBS_GMP_ARCHIVE) $(EXTLIBS_GMP_MKF)
	mkdir -p $(BLDABS_EXTLIBS_GMP_PREFIX) $(@D) && \
	cd $(BLDABS_EXTLIBS_GMP_PREFIX) && \
	tar xfz $(EXTLIBS_GMP_ARCHIVE) && \
	cd $(EXTLIBS_GMP_NAME) && \
	./configure \
	  --libdir=$(INSTALLABS_EXTLIBS_GMP_LIB_PREFIX) \
	  --includedir=$(INSTALLABS_EXTLIBS_GMP_INC_PREFIX) \
	  && \
	make && \
	make install && \
	touch $@

#	  --prefix=$(INSTALLABS_EXTLIBS_GMP_PREFIX) \
