/* ehclib/uhcbase/include/MachDeps.h.  Generated from MachDeps.h.in by configure.  */
#ifndef MACHDEPS_H
#define MACHDEPS_H

#define SIZEOF_INTPTR_T 8
#define SIZEOF_CHAR 1
#define SIZEOF_SHORT 2
#define SIZEOF_INT 4
#define SIZEOF_LONG 8
#define SIZEOF_LONG_LONG 8
#define SIZEOF_FLOAT 4
#define SIZEOF_DOUBLE 8
#define SIZEOF_UNSIGNED_CHAR 1
#define SIZEOF_UNSIGNED_SHORT 2
#define SIZEOF_UNSIGNED_INT 4
#define SIZEOF_UNSIGNED_LONG 8
#define SIZEOF_UNSIGNED_LONG_LONG 8
#define SIZEOF_VOID_P 8

#define SIZEOF_DEV_T 8
#define SIZEOF_INO_T 8
#define SIZEOF_OFF_T 8
#define SIZEOF_MODE_T 4
#define SIZEOF_PID_T 4
#define SIZEOF_SSIZE_T 8
#define SIZEOF_GID_T 4
#define SIZEOF_NLINK_T 8
#define SIZEOF_UID_T 4
#define SIZEOF_RLIM_T 8
#define SIZEOF_CLOCK_T 8
#define SIZEOF_TIME_T 8
#define SIZEOF_SIZE_T 8
#define SIZEOF_WCHAR_T 4

#define SIZEOF_CC_T 1
#define SIZEOF_SPEED_T 4
#define SIZEOF_TCFLAG_T 4

#define ALIGNOF_INTPTR_T 8
#define ALIGNOF_CHAR 1
#define ALIGNOF_SHORT 2
#define ALIGNOF_INT 4
#define ALIGNOF_LONG 8
#define ALIGNOF_LONG_LONG 8
#define ALIGNOF_FLOAT 4
#define ALIGNOF_DOUBLE 8
#define ALIGNOF_UNSIGNED_CHAR 1
#define ALIGNOF_UNSIGNED_SHORT 2
#define ALIGNOF_UNSIGNED_INT 4
#define ALIGNOF_UNSIGNED_LONG 8
#define ALIGNOF_UNSIGNED_LONG_LONG 8
#define ALIGNOF_VOID_P 8

#define ALIGNOF_UINT8_T 1
#define ALIGNOF_UINT16_T 2
#define ALIGNOF_UINT32_T 4
#define ALIGNOF_UINT64_T 8

#if SIZEOF_INTPTR_T == 8
#define USE_64_BITS 1
#define USE_32_BITS 0
#else
#define USE_64_BITS 0
#define USE_32_BITS 1
#endif

#ifdef __UHC_TARGET_BC__
#define BITSIZEOF_WORDTAG		1
#else
#define BITSIZEOF_WORDTAG		0
#endif

#define SIZEOF_HSCHAR           SIZEOF_INTPTR_T
#define ALIGNMENT_HSCHAR        ALIGNOF_UINT32_T

#define SIZEOF_HSINT            SIZEOF_INTPTR_T
#define ALIGNMENT_HSINT         ALIGNOF_INTPTR_T

#define SIZEOF_HSWORD			SIZEOF_INTPTR_T
#define ALIGNMENT_HSWORD		ALIGNOF_INTPTR_T

#define SIZEOF_HSDOUBLE			SIZEOF_DOUBLE
#define ALIGNMENT_HSDOUBLE		ALIGNOF_DOUBLE

#define SIZEOF_HSFLOAT			SIZEOF_FLOAT
#define ALIGNMENT_HSFLOAT		ALIGNOF_FLOAT

#define SIZEOF_HSPTR            SIZEOF_VOID_P
#define ALIGNMENT_HSPTR         ALIGNOF_VOID_P

#define SIZEOF_HSFUNPTR         SIZEOF_VOID_P
#define ALIGNMENT_HSFUNPTR      ALIGNOF_VOID_P

#define SIZEOF_HSFOREIGNPTR     SIZEOF_VOID_P
#define ALIGNMENT_HSFOREIGNPTR  ALIGNOF_VOID_P

#define SIZEOF_HSSTABLEPTR      SIZEOF_VOID_P
#define ALIGNMENT_HSSTABLEPTR   ALIGNOF_VOID_P

#define SIZEOF_INT8             8
#define ALIGNMENT_INT8          ALIGNOF_UINT8_T

#define SIZEOF_WORD8            8
#define ALIGNMENT_WORD8         ALIGNOF_UINT8_T

#define SIZEOF_INT16            16
#define ALIGNMENT_INT16         ALIGNOF_UINT16_T

#define SIZEOF_WORD16           16
#define ALIGNMENT_WORD16        ALIGNOF_UINT16_T

#define SIZEOF_INT32            32
#define ALIGNMENT_INT32         ALIGNOF_UINT32_T

#define SIZEOF_WORD32           32
#define ALIGNMENT_WORD32        ALIGNOF_UINT32_T

#define SIZEOF_INT64            64
#define ALIGNMENT_INT64         ALIGNOF_UINT64_T

#define SIZEOF_WORD64           64
#define ALIGNMENT_WORD64        ALIGNOF_UINT64_T


#endif
