RULER3_EXPR_EXPR_MAIN_SRC_AG := $(patsubst %,$(SRC_RULER3_PREFIX)%.cag,Expr/Expr)
RULER3_EXPR_EXPR_DPDS_SRC_AG := $(patsubst %,$(RULER3_BLD_PREFIX)%.ag, Expr/AbsSynAG)
$(patsubst $(SRC_RULER3_PREFIX)%.ag,$(RULER3_BLD_PREFIX)%.hs,$(RULER3_EXPR_EXPR_MAIN_SRC_AG)) : $(RULER3_EXPR_EXPR_DPDS_SRC_AG)

RULER3_TY_TY_MAIN_SRC_AG := $(patsubst %,$(SRC_RULER3_PREFIX)%.cag,Ty/Ty)
RULER3_TY_TY_DPDS_SRC_AG := $(patsubst %,$(RULER3_BLD_PREFIX)%.ag, Ty/AbsSynAG)
$(patsubst $(SRC_RULER3_PREFIX)%.ag,$(RULER3_BLD_PREFIX)%.hs,$(RULER3_TY_TY_MAIN_SRC_AG)) : $(RULER3_TY_TY_DPDS_SRC_AG)

RULER3_ABSSYN_ABSSYN1_MAIN_SRC_AG := $(patsubst %,$(SRC_RULER3_PREFIX)%.cag,AbsSyn/AbsSyn1)
RULER3_ABSSYN_ABSSYN1_DPDS_SRC_AG := $(patsubst %,$(RULER3_BLD_PREFIX)%.ag, AbsSyn/AbsSyn1AG AbsSyn/CommonAG)
$(patsubst $(SRC_RULER3_PREFIX)%.ag,$(RULER3_BLD_PREFIX)%.hs,$(RULER3_ABSSYN_ABSSYN1_MAIN_SRC_AG)) : $(RULER3_ABSSYN_ABSSYN1_DPDS_SRC_AG)

RULER3_ABSSYN_ABSSYN2_MAIN_SRC_AG := $(patsubst %,$(SRC_RULER3_PREFIX)%.cag,AbsSyn/AbsSyn2)
RULER3_ABSSYN_ABSSYN2_DPDS_SRC_AG := $(patsubst %,$(RULER3_BLD_PREFIX)%.ag, AbsSyn/AbsSyn2AG AbsSyn/CommonAG)
$(patsubst $(SRC_RULER3_PREFIX)%.ag,$(RULER3_BLD_PREFIX)%.hs,$(RULER3_ABSSYN_ABSSYN2_MAIN_SRC_AG)) : $(RULER3_ABSSYN_ABSSYN2_DPDS_SRC_AG)

RULER3_VIEWSEL_VIEWSEL_MAIN_SRC_AG := $(patsubst %,$(SRC_RULER3_PREFIX)%.cag,ViewSel/ViewSel)
RULER3_VIEWSEL_VIEWSEL_DPDS_SRC_AG := $(patsubst %,$(RULER3_BLD_PREFIX)%.ag, ViewSel/AbsSynAG)
$(patsubst $(SRC_RULER3_PREFIX)%.ag,$(RULER3_BLD_PREFIX)%.hs,$(RULER3_VIEWSEL_VIEWSEL_MAIN_SRC_AG)) : $(RULER3_VIEWSEL_VIEWSEL_DPDS_SRC_AG)

RULER3_ARULE_ARULE_MAIN_SRC_AG := $(patsubst %,$(SRC_RULER3_PREFIX)%.cag,ARule/ARule)
RULER3_ARULE_ARULE_DPDS_SRC_AG := $(patsubst %,$(RULER3_BLD_PREFIX)%.ag, ARule/AbsSynAG)
$(patsubst $(SRC_RULER3_PREFIX)%.ag,$(RULER3_BLD_PREFIX)%.hs,$(RULER3_ARULE_ARULE_MAIN_SRC_AG)) : $(RULER3_ARULE_ARULE_DPDS_SRC_AG)


RULER3_AG_D_DPDS_SRC_AG := $(sort $(RULER3_EXPR_EXPR_DPDS_SRC_AG) $(RULER3_TY_TY_DPDS_SRC_AG) $(RULER3_ABSSYN_ABSSYN1_DPDS_SRC_AG) $(RULER3_ABSSYN_ABSSYN2_DPDS_SRC_AG) $(RULER3_VIEWSEL_VIEWSEL_DPDS_SRC_AG) $(RULER3_ARULE_ARULE_DPDS_SRC_AG))

RULER3_AG_D_MAIN_SRC_AG := $(RULER3_EXPR_EXPR_MAIN_SRC_AG) $(RULER3_TY_TY_MAIN_SRC_AG) $(RULER3_ABSSYN_ABSSYN1_MAIN_SRC_AG) $(RULER3_ABSSYN_ABSSYN2_MAIN_SRC_AG) $(RULER3_VIEWSEL_VIEWSEL_MAIN_SRC_AG) $(RULER3_ARULE_ARULE_MAIN_SRC_AG)
