#!/bin/bash

# compile via grin.lua script 
# grin.lua expect to compile grin files via ../8/grc

#qc--.opt or just qc--
cmmc=qc--.opt
which "${cmmc}" >& /dev/null || cmmc=qc--

in="../${1}"
out="../${1%.*}"
shift

cd cmm
${cmmc} eh.lua grin.lua peephole.lua -globals startup.cmm "${in}" -o "${out}" -lgc "$@"
